### ISSUE TITLE
Evaluation codebase link in ProPara leaderboard is broken

### ISSUE THREAD

**Issue by nikett** [allenai/aristo-leaderboard#6]
Minor bug but      

On the ProPara leaderboard page, the link in this line is broken: 
"More information can be found on the leaderboard and **evaluator codebase** webpages."  

Current: https://github.com/allenai/aristo-leaderboard/tree/master/propara%20webpages
Expected: https://github.com/allenai/aristo-leaderboard/tree/master/propara

**Comment by aimichal** [comment]
This is the page with the broken link: http://data.allenai.org/propara/

I'll notify someone about this internally and update here when it's fixed.

**Comment by aimichal** [comment]
Fixed. You might have to shift-reload the page to see the update.
